const NUMBER_OF_POKEMON = 807;
const NUM_POKEMON_WITH_ALT_FORMS = 1026;
const NUMBER_OF_TABLES = 4;
const NUMBER_OF_TYPES = 18;
const TOTAL_POKEMON_WITH_TYPES = 1575;
const SPRITE_PATH = '/sprites/pokemon/';

module.exports = {
  NUMBER_OF_POKEMON,
  NUM_POKEMON_WITH_ALT_FORMS,
  NUMBER_OF_TABLES,
  NUMBER_OF_TYPES,
  TOTAL_POKEMON_WITH_TYPES,
  SPRITE_PATH,
};
