const NUMBER_OF_POKEMON = 806;
const NUMBER_OF_TABLES = 4;
const NUMBER_OF_TYPES = 18;
const TOTAL_POKEMON_WITH_TYPES = 1211;

module.exports = {
  NUMBER_OF_POKEMON,
  NUMBER_OF_TABLES,
  NUMBER_OF_TYPES,
  TOTAL_POKEMON_WITH_TYPES,
};
