const NUMBER_OF_POKEMON = 1007;
const NUMBER_OF_TABLES = 3;
const NUMBER_OF_TYPES = 18;
const TOTAL_POKEMON_WITH_TYPES = 1211;
const SPRITE_PATH = '/sprites/pokemon/';

module.exports = {
  NUMBER_OF_POKEMON,
  NUMBER_OF_TABLES,
  NUMBER_OF_TYPES,
  TOTAL_POKEMON_WITH_TYPES,
  SPRITE_PATH,
};
