CREATE TABLE public.damage_stats (
  type_1 INTEGER, 
  type_2 INTEGER, 
  normal NUMERIC(4,3),
  fire NUMERIC(4,3),
  water NUMERIC(4,3),
  electric NUMERIC(4,3),
  grass NUMERIC(4,3),
  ice NUMERIC(4,3),
  fighting NUMERIC(4,3),
  poison NUMERIC(4,3),
  ground NUMERIC(4,3),
  flying NUMERIC(4,3),
  psychic NUMERIC(4,3),
  bug NUMERIC(4,3),
  rock NUMERIC(4,3),
  ghost NUMERIC(4,3),
  dragon NUMERIC(4,3),
  dark NUMERIC(4,3),
  steel NUMERIC(4,3),
  fairy NUMERIC(4,3),
  CONSTRAINT damage_stats_key PRIMARY KEY (type_1, type_2))